# Generated by Django 5.2.8 on 2026-02-25 23:40

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0078_alter_subscriptionplanrenewal_salesforce_opportunity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feature Permission',
                'verbose_name_plural': 'Feature Permissions',
            },
        ),
        migrations.AddField(
            model_name='historicallicense',
            name='consumption_date',
            field=models.DateTimeField(blank=True, help_text='Set when this license is first assigned/consumed.', null=True),
        ),
        migrations.AddField(
            model_name='historicallicense',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When null, the license is perpetual.', null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='consumption_date',
            field=models.DateTimeField(blank=True, help_text='Set when this license is first assigned/consumed.', null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When null, the license is perpetual.', null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='feature_permissions',
            field=models.ManyToManyField(blank=True, related_name='licenses', to='subscriptions.featurepermission'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='feature_permissions',
            field=models.ManyToManyField(blank=True, related_name='plans', to='subscriptions.featurepermission'),
        ),
    ]
