# Generated by Django 5.2.8 on 2026-02-25 23:45

from django.db import migrations


DEFAULT_CATALOG_FEATURE_SLUG = 'catalog.curated_access'
DEFAULT_CATALOG_FEATURE_NAME = 'Catalog Curated Access'


def _chunks(items, chunk_size):
    for idx in range(0, len(items), chunk_size):
        yield items[idx:idx + chunk_size]


def backfill_feature_permissions_and_expiry(apps, schema_editor):
    FeaturePermission = apps.get_model('subscriptions', 'FeaturePermission')
    License = apps.get_model('subscriptions', 'License')

    default_permission, _ = FeaturePermission.objects.get_or_create(
        slug=DEFAULT_CATALOG_FEATURE_SLUG,
        defaults={'name': DEFAULT_CATALOG_FEATURE_NAME},
    )

    # Backfill old licenses to preserve historical time-limited behavior.
    licenses_to_update = []
    for license_obj in License.objects.select_related('subscription_plan').filter(expires_at__isnull=True).iterator():
        license_obj.expires_at = license_obj.subscription_plan.expiration_date
        licenses_to_update.append(license_obj)

        if len(licenses_to_update) >= 1000:
            License.objects.bulk_update(licenses_to_update, ['expires_at'])
            licenses_to_update = []

    if licenses_to_update:
        License.objects.bulk_update(licenses_to_update, ['expires_at'])

    through_model = License.feature_permissions.through

    license_ids_without_permissions = list(
        License.objects.filter(feature_permissions__isnull=True).values_list('uuid', flat=True)
    )
    through_objects = [
        through_model(
            license_id=license_id,
            featurepermission_id=default_permission.id,
        ) for license_id in license_ids_without_permissions
    ]
    for through_batch in _chunks(through_objects, 1000):
        through_model.objects.bulk_create(through_batch, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0079_featurepermission_historicallicense_consumption_date_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_feature_permissions_and_expiry,
            migrations.RunPython.noop,
        ),
    ]

