# Generated by Django 5.2.8 on 2026-02-26 15:38

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0080_backfill_feature_permissions_and_license_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feature Role',
                'verbose_name_plural': 'Feature Roles',
            },
        ),
        migrations.AddField(
            model_name='license',
            name='feature_roles',
            field=models.ManyToManyField(blank=True, related_name='licenses', to='subscriptions.featurerole'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='feature_roles',
            field=models.ManyToManyField(blank=True, related_name='plans', to='subscriptions.featurerole'),
        ),
    ]
